# Generated by Django 5.1.4 on 2024-12-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('recurrence', models.CharField(choices=[('Y', 'Anual'), ('M', 'Mensal'), ('W', 'Semanal'), ('N', 'Sem')], default='N', max_length=1, verbose_name='Recorrência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('history', models.CharField(max_length=200, verbose_name='Histórico')),
                ('due_date', models.CharField(blank=True, help_text='Formato aceito DD-MM', max_length=5, null=True, verbose_name='Vencimento')),
            ],
            options={
                'verbose_name': 'Débito',
                'verbose_name_plural': 'Débitos',
            },
        ),
    ]
