# Generated by Django 5.1.4 on 2025-01-08 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0006_credit_deactivated_at'),
        ('debts', '0006_debt_deactivated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credits.credit', verbose_name='Cartão de credito'),
        ),
    ]
