# Generated by Django 5.1.4 on 2025-01-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0008_alter_debt_credit_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Bank Transfer', 'Bank Transfer'), ('Digital Wallet', 'Digital Wallet'), ('Cryptocurrency', 'Cryptocurrency'), ('Check', 'Check'), ('Other', 'Other')], default='Cash', max_length=50, verbose_name='Método de pagamento'),
        ),
    ]
