# Generated by Django 5.1.4 on 2025-01-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0009_debt_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('DIGITAL_WALLET', 'Digital Wallet'), ('CRYPTOCURRENCY', 'Cryptocurrency'), ('CHECK', 'Check'), ('OTHER', 'Other')], default='CASH', max_length=50, verbose_name='Método de pagamento'),
        ),
    ]
