# Generated by Django 5.1.4 on 2025-01-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0010_alter_debt_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Dinheiro'), ('CREDIT_CARD', 'Cartão de crédito'), ('DEBIT_CARD', 'Cartão de débito'), ('BANK_TRANSFER', 'Transferencia bancária'), ('DIGITAL_WALLET', 'Digitall wallet'), ('CRYPTOCURRENCY', 'Cryptocurrency'), ('CHECK', 'Check'), ('OTHER', 'Other')], default='CASH', max_length=50, verbose_name='Método de pagamento'),
        ),
    ]
