# Generated by Django 5.1.4 on 2024-12-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0005_alter_credit_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desativado em'),
        ),
    ]
