# Generated by Django 5.1.4 on 2025-06-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credits", "0007_remove_credit_user_credit_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="history",
            field=models.JSONField(blank=True, default=list, verbose_name="Histórico"),
        ),
    ]
