version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A src worker -E -l debug
    volumes:
      - .:/app
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/financeman"
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - db
      - redis

  beat:
    build: .
    command: celery -A src beat --loglevel=debug
    volumes:
      - .:/app
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/financeman"
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - db
      - redis


volumes:
  data:
