# Generated by Django 5.1.4 on 2024-12-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_goal_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='concluded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desativado em'),
        ),
    ]
