# Generated by Django 5.1.4 on 2024-12-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='concluded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Executado em'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fornecedor'),
        ),
    ]
