# Generated by Django 5.1.4 on 2024-12-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_contribution_concluded_at_contribution_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='concluded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluído em'),
        ),
    ]
