# Generated by Django 5.1.4 on 2025-01-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_supplier_contribution_supplier_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='rating',
            field=models.IntegerField(choices=[(1, '0.5 estrelas'), (2, '1.0 estrelas'), (3, '1.5 estrelas'), (4, '2.0 estrelas'), (5, '2.5 estrelas'), (6, '3.0 estrelas'), (7, '3.5 estrelas'), (8, '4.0 estrelas'), (9, '4.5 estrelas')], default=0, verbose_name='Avaliação'),
        ),
    ]
