# Generated by Django 5.1.4 on 2025-02-06 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_alter_supplier_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='supplier',
        ),
    ]
