# Generated by Django 5.1.4 on 2025-02-06 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_remove_contribution_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='supplier_new',
            new_name='supplier',
        ),
    ]
