# Generated by Django 5.1.4 on 2025-02-18 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0011_rename_supplier_new_contribution_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='goals.supplier', verbose_name='Fornecedor'),
        ),
    ]
