# Generated by Django 5.1.4 on 2025-04-12 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0013_remove_contribution_user_remove_goal_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='goals.goal', verbose_name='Objetivo pai'),
        ),
    ]
