# Generated by Django 5.1.4 on 2025-04-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0014_goal_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='concluded_at',
            field=models.DateField(blank=True, null=True, verbose_name='Executado em'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='canceled_at',
            field=models.DateField(blank=True, null=True, verbose_name='Cancelado em'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='concluded_at',
            field=models.DateField(blank=True, null=True, verbose_name='Concluído em'),
        ),
    ]
