# Generated by Django 5.1.4 on 2025-04-29 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0015_alter_contribution_concluded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_goals', to='goals.goal', verbose_name='Objetivo pai'),
        ),
    ]
