# Generated by Django 5.1.4 on 2025-05-01 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0016_alter_goal_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='users',
        ),
    ]
