# Generated by Django 5.1.4 on 2025-05-02 20:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0017_remove_contribution_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='concluded_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Executado em'),
        ),
    ]
