# Generated by Django 5.1.4 on 2025-05-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0018_alter_contribution_concluded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Desconto (%)'),
        ),
    ]
