# Generated by Django 5.1.4 on 2025-05-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0019_contribution_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto (%)'),
        ),
    ]
