# Generated by Django 5.1.4 on 2025-06-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0020_alter_contribution_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="history",
            field=models.JSONField(blank=True, null=True, verbose_name="Histórico"),
        ),
    ]
