# Generated by Django 5.1.4 on 2025-06-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0021_alter_goal_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="history",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Histórico"),
        ),
    ]
