# Generated by Django 5.1.4 on 2025-06-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0022_alter_goal_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="deactivated_at",
            field=models.DateField(blank=True, null=True, verbose_name="Desativado em"),
        ),
    ]
