# Generated by Django 5.1.4 on 2025-06-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0023_goal_deactivated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="history",
            field=models.JSONField(blank=True, default=list, verbose_name="Histórico"),
        ),
    ]
