# Generated by Django 5.1.4 on 2025-07-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0024_alter_goal_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goal",
            name="history",
        ),
        migrations.AddField(
            model_name="contribution",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
        ),
    ]
