# Generated by Django 5.1.4 on 2025-07-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0025_remove_goal_history_contribution_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "1 estrelas"),
                    (2, "2 estrelas"),
                    (3, "3 estrelas"),
                    (4, "4 estrelas"),
                ],
                default=0,
                verbose_name="Avaliação",
            ),
        ),
    ]
