# Generated by Django 5.1.4 on 2024-12-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('recurrence', models.CharField(choices=[('YEAR', 'Anual'), ('MONTHLY', 'Mensal'), ('WEEK', 'Semanal'), ('N', 'Sem')], default='N', max_length=50, verbose_name='Recorrência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('history', models.CharField(max_length=200, verbose_name='Histórico')),
                ('category', models.CharField(choices=[('POST_FIXED', 'Pós-Fixado'), ('PRE_FIXED', 'Pré-Fixado'), ('HYBRID', 'Híbrido'), ('VARIABLE', 'Renda Variável'), ('STOCK', 'Ações'), ('FUND', 'Fundo de Investimento'), ('REAL_ESTATE', 'Imóveis'), ('CRYPTOCURRENCY', 'Criptomoedas'), ('SAVINGS', 'CDI')], default='SAVINGS', max_length=50, verbose_name='Categoria')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taxa de Juros')),
                ('post_fixed_index', models.CharField(blank=True, help_text='Índice de pós-fixação, como Selic, IPCA, etc.', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
            },
        ),
    ]
