# Generated by Django 5.1.4 on 2024-12-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_alter_investment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='due_date',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Dia do vencimento'),
        ),
    ]
