# Generated by Django 5.1.4 on 2025-07-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0007_remove_investment_user_investment_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investment",
            name="history",
        ),
    ]
