# Generated by Django 5.1.4 on 2024-12-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnings',
            name='recurrence',
            field=models.CharField(choices=[('Y', 'Anual'), ('M', 'Mensal'), ('W', 'Semanal'), ('N', 'Sem')], default='N', max_length=1),
        ),
    ]
