# Generated by Django 5.1.4 on 2024-12-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0002_alter_earnings_recurrence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earnings',
            options={'verbose_name': 'Ativo', 'verbose_name_plural': 'Ativos'},
        ),
        migrations.AddField(
            model_name='earnings',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='history',
            field=models.CharField(max_length=200, verbose_name='Histórico'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='recurrence',
            field=models.CharField(choices=[('Y', 'Anual'), ('M', 'Mensal'), ('W', 'Semanal'), ('N', 'Sem')], default='N', max_length=1, verbose_name='Recorrência'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado em'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
