# Generated by Django 5.1.4 on 2024-12-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0007_alter_earnings_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnings',
            name='payment_day',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Dia do recebimento'),
        ),
    ]
