# Generated by Django 5.1.4 on 2024-12-23 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0008_alter_earnings_payment_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('recurrence', models.CharField(choices=[('YEAR', 'Anual'), ('MONTHLY', 'Mensal'), ('WEEK', 'Semanal'), ('N', 'Sem')], default='N', max_length=50, verbose_name='Recorrência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('history', models.CharField(blank=True, max_length=200, null=True, verbose_name='Histórico')),
                ('payment_day', models.CharField(blank=True, max_length=5, null=True, verbose_name='Dia do recebimento')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desativado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
            },
        ),
        migrations.DeleteModel(
            name='Earnings',
        ),
    ]
