# Generated by Django 5.1.4 on 2025-01-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0009_earning_delete_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Válido até'),
        ),
    ]
