# Generated by Django 5.1.4 on 2025-06-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("earnings", "0012_remove_earning_user_earning_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="earning",
            name="history",
            field=models.JSONField(blank=True, default=list, verbose_name="Histórico"),
        ),
    ]
