# Generated by Django 5.1.4 on 2025-07-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("earnings", "0013_alter_earning_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="earning",
            name="history",
        ),
    ]
