# Generated by Django 5.1.4 on 2024-12-23 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desativado em'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='index',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Índice'),
        ),
    ]
