# Generated by Django 5.1.4 on 2024-12-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_parameter_created_at_parameter_deactivated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='index',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Índice'),
        ),
    ]
