# Generated by Django 5.1.4 on 2025-06-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parameters", "0004_remove_parameter_user_parameter_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parameter",
            name="history",
            field=models.JSONField(blank=True, default=list, verbose_name="Histórico"),
        ),
    ]
