# Generated by Django 5.1.4 on 2025-07-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parameters", "0005_alter_parameter_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parameter",
            name="history",
        ),
    ]
